# -*- coding: utf-8 -*-
"""lvadsusr194_varundas_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SpzHOFEoKNJtTpuquvWqz4U-B1jkeRze
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings as wr
wr.filterwarnings('ignore')

"""1(a).Data importation"""

data=pd.read_csv('/content/Final Dataset - IPL.csv')
data

"""1(b).structure and content"""

data.shape

data.head()

data.describe()

data.dtypes

data.isnull().sum()

"""2.Data Cleaning

2(a).Missing Values
"""

data.isnull().sum()

"""There are no missing values in these data set and hence there no need to fill or drop any data.

2(b).Duplicates
"""

dup=data.duplicated().sum()
dup

data.drop_duplicates(inplace=True)

data.shape

"""We have checked the shape before and after dropping the duplicates.Both the shape are same and also checked the sum of duplicates.With this we can conclude that the data doesn't have any duplicate values.

3.Descriptive Statics
"""

calc=data[['first_ings_score','first_ings_wkts','second_ings_score','second_ings_wkts','margin','highscore']]
Mean=calc.mean()
Mean

Median=calc.median()
Median

Mode=calc.mode()
Mode

Range=calc.max()-calc.min()
Range

Varience=calc.var()
Varience

Std=calc.std()
Std

"""The mean,median,mode,range,variance and standard deviation of the numerical column from the dataset is given.From that we can able to understand the central tendencies and variability of the data.

4.Data Visualizatin
"""

#Histogram:

data['first_ings_score'].plot(kind='hist', bins=20, title='first_ings_score')
plt.gca().spines[['top', 'right',]].set_visible(False)

"""The above Graph shows the histogram graph from the first innings score.From this graph we can conclude that the values not not skewed and it is a SD."""

#Scatter Plot

data.plot(kind='scatter', x='first_ings_score', y='first_ings_wkts', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

"""The scatter plot shows relationship between the first innings wicket and the first innings score."""

#Box Plot

sns.boxplot(data['second_ings_score'])

"""From the above boxplot we can conclude that there are only 2 outlier values in our second innings score data from the dataset"""

#Bar Graph

import seaborn as sns
data.groupby('toss_decision').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

"""The Bar graph shows the toss decisions of the teams."""

#Line Chart

data['first_ings_score'].plot(kind='line', figsize=(8, 4), title='first_ings_score')
plt.gca().spines[['top', 'right']].set_visible(False)

"""This line plot shows the distribution of scores from the first innings by the playes

5.Identifying Relationships
"""

cor=data[['first_ings_score','first_ings_wkts','second_ings_score','second_ings_wkts','margin','highscore']]
c=cor.corr()
sns.heatmap(c,annot=True)

"""From the above we can easily conclude the relationships between the data.We can easily see that the first innings wicket is affecting the score for the playes in their first innings score.

6.Outliers Detection
"""

sns.boxplot(data['first_ings_score'])

"""The first innings score have vey less outlier we don't have to traet it.That is because the dataset we have is a cricket matches dataset.So here outliers are possible and hence we don't have to remove it."""

sns.boxplot(data['first_ings_wkts'])

"""The first innings wicket have vey less outlier we don't have to traet it.That is because the dataset we have is a cricket matches dataset.So here outliers are possible and hence we don't have to remove it."""

sns.boxplot(data['second_ings_score'])

"""The second innings score have vey less outlier we don't have to traet it.That is because the dataset we have is a cricket matches dataset.So here outliers are possible and hence we don't have to remove it."""

sns.boxplot(data['second_ings_wkts'])

"""Here in second innings wicket there are no outliers present and hence we don't have to treat it."""

sns.boxplot(data['margin'])

"""The margin have outliers we don't have to traet it.That is because the dataset we have is a cricket matches dataset.So here outliers are possible and hence we don't have to remove it."""

sns.boxplot(data['highscore'])

"""The second innings score have vey less outlier we don't have to traet it.That is because the dataset we have is a cricket matches dataset.So here outliers are possible and hence we don't have to remove it.Each and every match the highscore can vary and it can give totally ouliered value that is comman in this dataset and hence we don't have to treat it.

7.Performance trends and venue impact
"""

import seaborn as sns
compare.groupby('venue').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

"""The above bar graph shows the performance across different matches."""

compare=data[['venue','match_winner']]
compare

from matplotlib import pyplot as plt
import seaborn as sns
comp=data[['venue','match_winner']].head(5)
sns.barplot(comp,x='venue',y='match_winner')

"""The above graph shows the matchs won by teams with respect to the venue

8.Player Spotlight
"""

data.head(5)

kp=data.groupby('player_of_the_match').value_counts()
plt(kp,type='line')
plt.show()

fil=data[['player_of_the_match','team1','team2','top_scorer','best_bowling']]
fil
kp=fil[('player_of_the_match')].value_counts()
kp

"""From this we can see that Kuldeep Yadav has the highest number of man of the match award."""

fil=data[['player_of_the_match','team1','team2','top_scorer','best_bowling']]
fil
kp=fil[('top_scorer')].value_counts()
kp

"""From this we can see that Jos Buttler is the top scorer from comparing all the matches."""

fil=data[['player_of_the_match','team1','team2','top_scorer','best_bowling']]
fil
kp=fil[('best_bowling')].value_counts()
kp

"""From this we can see that Yuzvendra Chahal is the best bowler among the others.

9.Data Discovery

Findings:

From doing all the procees we can come to a conclusion.That is the person who got man of the match award in most of the matches is Kuldeep Yadav.And the person who scored highest score in many matches in that series is Jos Buttler.And the man who has taken more wickest and the best bowler in most of the matches is Yuzvendra Chahal.

Insights:

From the data we can get to know about the teams who have played in different venues and the matches they have won and the total wickets they have taken and the total runs they have scored from both the first and second innings and also we get to know about the man of the match in most of the matchs and the person who scored more runs in most of the matches and the person who took a lot of wickets in these series.Also we get to know about which team is performong well in which veue and which venue is suitable for battinga and which one is well suited for bowling.

Outcomes:

From the above data set we got all the informations such as best man of the match and the best batsman who scores highest number of runs and the best bowler who took a lot of wickets in these series.And also about the venue where the matches were held.
Using these details we can make the cricket team more stronger and plan the statistics and strategy for the matchs accordingly.
We came to know about which person will score more in which venue and which bowler will take more wickets in which venue.And also most importantly which team will perform well in wich venue and bad in which venue.These outcomes from this dataset will be very useful for the teams to practice and make strategies accordingly.
"""