# -*- coding: utf-8 -*-
"""LVADSUSR194_VarunDas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDvizfj2k9AEdKK_-YvHv3U5hikMUk7v
"""

#1

def area(length,breadth):
  area=length*breadth
  print("The area is : ",area)
  if area>1000:
    print("The area is large")
  elif area>500 and area<1000:
    print("The area is medium")
  else:
    print("The area is small")

length=int(input("Enter the length in metres: "))
width=int(input("Enter the width in metres: "))

calc=area(length,width)
print(calc)

#2:

def bmi(weight,height):
  bmi=weight/height**2
  return bmi
  if bmi>30:
    print("Your weight is heigh you have to reduce it")
  elif bmi>15 and bmi<30:
    print("Your height and weight are normal")
  else:
    print("Your weight is low you have to increase it")


weight=float(input("Enter the weight: "))
height=float(input("Enter the height in metres: "))

calc=bmi(weight,height)
print("Your bmi is: ")
print(calc)

#3

students={"tamil":70,"English":90,"Maths":80,"Physics":95,"Chemistry":84}

#4

age = int(input("Enter your age: "))

if age>60:
  print("The movies recomended for Seniors are gives below")
elif age>18 and age<60:
  print("The movies recomended for Adults are gives below")
elif age>18 and age<60:
  print("The movies recomended for teen are gives below")
else:
  print("The movies recomended for children are gives below")

#5

id = [1,2,3,4,5,6,7,8]
e_id=[]

for i in range(1,len(id)+1):
  if i%2==0:
    e_id.append(i)

print("The students who have even numbered ids are listed: ",e_id)

#6

saved_pass="hello"

while True:

  a=(input("Enter the password: "))

  if a == saved_pass:
      print("Your password is correct")
      break
  else:
      print("Your password is incorrect retry")

#7

rating = [4,3,5,2,1,5,4,2]
sum=0

for i in range(len(rating)):
  sum=sum+rating[i]

avg=sum/len(rating)

print("The average score is: ",avg)
if avg>4:
  print("The customer is satisfied")
elif avg>2.5 and avg<4:
  print("The scores are okay")
else:
  print("Need to improve")

#8

def vowel():
  str=input("Enter the string: ")
  ans=0

  for i in range(len(str)):
    if str[i]=="a" or str[i]=="e" or str[i]=="i" or str[i]=="o" or str[i]=="u":
      ans=ans+1

  print("There are a total of",ans,"Vowels in this string")

ans=vowel()
print(ans)

#9

import datetime

date=datetime.datetime.now()
print(date)

#10

def si(p,n,r):
    si=p*n*r/100
    print("The interest is ",si)


try:
  p=int(input("enter the vale: "))
  n=int(input("enter the vale: "))
  r=int(input("enter the vale: "))
  calc = si(p,n,r)
  print(calc)
except ValueError:
    print("Give proper values for p,n,r")

#11

while True:
  a=int(input("Enter the number from 1-10 to vote: "))
  if a <= 10:
    print("Your vote has been captuted")
    break
  else:
    print("Your vote has not been captuted please enter a number within 1-10 to vote")

#12

while True:
  try:
    a=int(input("Enter the first number: "))
    b=int(input("Enter the second number: "))
    c=a/b
    print(c)
    break
  except ZeroDivisionError:
    print("The Denominator value should not be 0")

#13

file=open("C:\\Users\\varun.das.lv\\Downloads\\practrw.txt",'w')
file.write('reort uptime')
file.close()

#14
file=open("C:\\Users\\varun.das.lv\\Downloads\\practrw.txt",'r')
print(file.read())
file.close()

#15

l=[]
a=input()
l.append(a)
file=open("C:\\Users\\varun.das.lv\\Downloads\\practrw.txt",'w')
file.writelines(l)
file.close()